### ISSUE TITLE
Plasma Addons Store?

### ISSUE THREAD

**Issue by sammyspark** [dwardor/plasma-applet-fanspeed-monitor#2]
Hey, this is super cool, thanks for making and sharing it with us!! Do you have any plans on adding it to the KDE Plasma Addons store?

**Comment by dwardor** [comment]
Good idea... Haven't even looked at how that would be done...

**Comment by dwardor** [comment]
I think I figured out what to put in the .plasmoid file...
See https://store.kde.org/p/1348495/

Can you test it ?

**Comment by sammyspark** [comment]
Looks like it downloads and installs perfectly, thanks so much! I see just one problem with it, but I'll make a separate request for that.
