### ISSUE TITLE
Length of applet on small taskbars

### ISSUE THREAD

**Issue by sammyspark** [dwardor/plasma-applet-fanspeed-monitor#3]
On smaller taskbars, the fanspeed gets cut off when the fan speed font size is at default size, as shown [here](http://i.imgur.com/N2JkQ4O.png). It would be really nice if instead of or in addition to the "Fan Speed Right Margin", we could have a "Fan Speed Applet Length" slider instead.

Also, if the sliders could have [numbers or spin boxes](https://hig.kde.org/components/editing/slider.html) to the right of them, that would be super awesome as well.

Thanks so much for the great applet and happy holidays!!

**Comment by sammyspark** [comment]
Oh also I've never worked with Plasma applets before but if you'd like, I can take a look at this myself in a couple days and try working on it. I don't wanna just take and not give back :sweat_smile:

**Comment by dwardor** [comment]
Could you give a screenshot to illustrate ?
I must admit I've copy pasted the widget size code from thermal monitor and just adjusted widget width to height ratio (1.6 if I remember well but can be increased) as rpm speed is usually 7 characters vs 3 for temperature (everything gets auto adjusted as soon as you resize the widget... Does Thermal monitor have the same issue ?

**Comment by sammyspark** [comment]
I attached a screenshot and a link above, but in case the Markdown didn't render correctly, here they are in raw form:

Screenshot of issue: http://i.imgur.com/N2JkQ4O.png
KDE Design tips for different types of sliders: https://hig.kde.org/components/editing/slider.html
(this was in reference to how I would prefer to see the font size that is being displayed)

**Comment by dwardor** [comment]
edit  .local/share/plasma/plasmoids/org.kde.fanspeedMonitor/contents/ui/main.qml

modify line 87 "itemWidth = itemHeight*1.6"
replace 1.6 something bigger (I'd start with 2.0)

save

reboot

--> Tell me what works for you. Maybe we can introduce a parameter for this 

Another solution is just to reduce Fan speed font size with slider ;-) !

**Comment by dwardor** [comment]
https://doc.qt.io/qt-5/qml-qtquick-controls-slider.html which are used do not seem to allow to show value

**Comment by dwardor** [comment]
Just uploaded v1.1.0 try playing with the new parameter "Width to Height ratio" and the new sliders with numbers

**Comment by sammyspark** [comment]
Hey, just downloaded v1.1.0 from the Plasma store, the applet looks the same as before except for the settings menu. The slider for "Width to Height ratio" does not change anything. Additionally the slider glitches out because some of the values [become very long due to floating point arithmetic](http://i.imgur.com/apxrDoY.png).

**Comment by dwardor** [comment]
Did you click "apply" after adjusting Width to Height parameter ? (it only recomputes widget size once you click apply)

**Comment by dwardor** [comment]
Try new upload, the glitch due to floating point arithmetic is corrected
Width to Height ratio has an effect here (after clicking apply)
![image](https://user-images.githubusercontent.com/50771662/71640242-94afa400-2c86-11ea-9de0-737faa7177db.png)
![image](https://user-images.githubusercontent.com/50771662/71640232-66ca5f80-2c86-11ea-9bcb-b16b327f2b0e.png)
![image](https://user-images.githubusercontent.com/50771662/71640281-84e48f80-2c87-11ea-8626-577f79501fb7.png)

Wigdet width is measured from left of C of "CPU" to right of m of "rpm" and has changed between the first 2 screenshots from 1.2 to 1.6. Last step is eventual manual resizing with mouse of "Parent Frame" (see last screenshot)

**Comment by dwardor** [comment]
No news good news ? I'll be closing the issue then...
