### ISSUE TITLE
stuck on ECM

### ISSUE THREAD

**Issue by jmordkoff** [dwardor/plasma-applet-fanspeed-monitor#6]
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.11) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

**Comment by dwardor** [comment]
See very first issue and solution : https://github.com/dwardor/plasma-applet-fanspeed-monitor/issues/1
