### ISSUE TITLE
No sources

### ISSUE THREAD

**Issue by DavidNemeskey** [dwardor/plasma-applet-fanspeed-monitor#7]
Hi! I added the widget to the desktop, then went on to add resources (which I figured I should do since the fan on the widget did not move), only to find that the dropdown is empty. Should I have some library installed, which I do not?

KDE Neon 5.22, kernel 5.4.0.74.

**Comment by dwardor** [comment]
Yep kde 5.22 seems to cause issues as lmsensors sources are not available anymore...

**Comment by dwardor** [comment]
Seems you need to install ksysguard (which kde5.22 replaced with systemmonitor) for lmsensors datasources to be available for the widget... See https://bbs.archlinux.org/viewtopic.php?id=267053

Can confirm installing ksysguard, and logging out of kde session and back in does the trick
