### ISSUE TITLE
Can't find plasma_install_package

### ISSUE THREAD

**Issue by ont4300** [dwardor/plasma-applet-fanspeed-monitor#9]
I am trying to build your latest version and fail due to the inability to find plasma_install_package.

I am running the latest version of OpenSUSE Tumbleweed and have all of your required packages installed.

The terminal session is: 

tom@brutus:~> git clone --depth=1 https://github.com/dwardor/plasma-applet-fanspeed-monitor
Cloning into 'plasma-applet-fanspeed-monitor'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 38 (delta 2), reused 24 (delta 0), pack-reused 0
Receiving objects: 100% (38/38), 810.50 KiB | 3.00 MiB/s, done.
Resolving deltas: 100% (2/2), done.
tom@brutus:~> cd plasma-applet-fanspeed-monitor/
tom@brutus:~/plasma-applet-fanspeed-monitor> ll
total 28
-rw-r--r-- 1 tom users   412 Sep 26 12:26 CMakeLists.txt
drwxr-xr-x 1 tom users    64 Sep 26 12:26 docs
-rw-r--r-- 1 tom users 18027 Sep 26 12:26 LICENSE
drwxr-xr-x 1 tom users    48 Sep 26 12:26 package
-rw-r--r-- 1 tom users  1092 Sep 26 12:26 README.md
drwxr-xr-x 1 tom users   134 Sep 26 12:26 translations
tom@brutus:~/plasma-applet-fanspeed-monitor> mkdir build
tom@brutus:~/plasma-applet-fanspeed-monitor> cd build
tom@brutus:~/plasma-applet-fanspeed-monitor/build> ll
total 0
tom@brutus:~/plasma-applet-fanspeed-monitor/build> cmake .. -DCMAKE_INSTALL_PREFIX=/usr
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No  executable found. Can't check QT_INSTALL_PREFIX
Installing in /usr. Run /home/tom/plasma-applet-fanspeed-monitor/build/prefix.sh to set the environment for Project.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning at CMakeLists.txt:13 (find_package):
  By not providing "FindKF5Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Plasma" with
  any of the following names:

    KF5PlasmaConfig.cmake
    kf5plasma-config.cmake

  Add the installation prefix of "KF5Plasma" to CMAKE_PREFIX_PATH or set
  "KF5Plasma_DIR" to a directory containing one of the above files.  If
  "KF5Plasma" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at CMakeLists.txt:17 (plasma_install_package):
  Unknown CMake command "plasma_install_package".

-- Configuring incomplete, errors occurred!
See also "/home/tom/plasma-applet-fanspeed-monitor/build/CMakeFiles/CMakeOutput.log".
tom@brutus:~/plasma-applet-fanspeed-monitor/build> 

The link to the session log is:

https://drive.google.com/file/d/1Kmx-qaeporetR5Y31iIF-Ef1GTOpOcT8/view?usp=sharing

Any suggestions???  Tom.

**Comment by dwardor** [comment]
1. Do you have plasma installed ?
plasma package is what provides KF5PlasmaConfig.cmake (that your system doesn't seem to find) on my distro (gentoo)

2. What does` locate KF5PlasmaConfig.cmake` return ?

3. is there a plasma-dev package that is available for install on opensuse tumbleweed by any chance ?

**Comment by dwardor** [comment]
seems it may be you need [plasma5-sdk tumbleweed package](https://software.opensuse.org/download/package?package=plasma5-sdk&project=openSUSE%3AFactory) taken from [here](https://software.opensuse.org/package/plasma5-sdk)

as the description seems interesting : 

> Plasma SDK taylored for development of Plasma components, such as Widgets, Runners, Dataengines.

**Comment by ont4300** [comment]
Hi.

locate KF5PlasmaConfig.cmake returned nothing. I installed the plasma5-sdk package as instructed but that didn't help. I discussed the situation with mister Google and he suggested a reference to plasma-framework-devel which was missing. I installed the package, and the widget was able to build with no errors. It created version 0.1 which I think is the wrong version. Just to be sure, I deleted the package, redid the build process and got the same result of version 0.1

When attempting to set it up, the "Add Resources" shows nothing.

Please advise... 
Thanks... Tom

**Comment by dwardor** [comment]
Thanks for catching that the version error on my side.
Do you have ksysgard installed ? See https://github.com/dwardor/plasma-applet-fanspeed-monitor/issues/7#issuecomment-877821103

**Comment by ont4300** [comment]
I installed kstsguard5 and everything worked fine. I have attached a screenshot so you can see the results. Perhaps you might include ksysguard5 in the list of dependencies.

Thanks for your help... Tom.

![Screenshot_20220927_160437](https://user-images.githubusercontent.com/24478202/192625875-839c9bd6-e901-4f97-a12f-6b5aca6d6159.png)

**Comment by dwardor** [comment]
Added the extra info in README.md and corrected Version
